common: &common
  adapter: postgresql
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: meal_planner_dev

test:
  <<: *common
  database: meal_planner_test

production:
  <<: *common
  database: meal_planner

